<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="M_PI" value="3.1415926535897931" />

  <xacro:macro name="pioneer_mount" params="name parent xyz rpy model_dir:=^">   
  <xacro:property name="mount_base_width" value="0.14" />
  <xacro:property name="mount_bar_width" value="0.02" />
        
  <!--  mount top bar -->
  <joint name="${parent}_top_bar_joint" type="fixed">
    <origin xyz="0 0 0.96" rpy="${rpy}"/>
    <parent link="${parent}"/>
    <child link="${name}_top_bar"/>
  </joint>
  <link name="${name}_top_bar">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${mount_bar_width} 0.385 ${mount_bar_width} "/>
      </geometry>
      <material name="${name}_top_bar">
        <color rgba="0.8 0.8 0.8 1"/>
      </material>
    </visual>
  </link>
  <gazebo reference="${name}_top_bar">
    <material value="Gazebo/Grey"/>
  </gazebo>
        
  
  <!--  mount camera tof -->
  <joint name="${parent}_camera_tof_joint" type="fixed">
    <origin xyz="0 0 0.51" rpy="${rpy}"/>
    <parent link="${parent}"/>
    <child link="${name}_camera_tof"/>
  </joint>
  <link name="${name}_camera_tof">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.12 0.12"/>
      </geometry>
      <material name="${name}_camera_tof">
        <color rgba="0.8 0.8 0.8 1"/>
      </material>
    </visual>
  </link>
  <gazebo reference="${name}_camera_tof">
    <material value="Gazebo/Grey"/>
  </gazebo>
  
  
  <!--  mount bottom left -->
  <joint name="${parent}_${name}_bottom_left_joint" type="fixed">
    <origin xyz="0.0 ${+mount_base_width} ${mount_bar_width/2.}" rpy="${rpy}"/>
    <parent link="${parent}"/>
    <child link="${name}_bottom_left"/>
  </joint>
  <link name="${name}_bottom_left">
    <visual>
      <origin xyz="-0.04 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.3 ${mount_bar_width} ${mount_bar_width}"/>
      </geometry>
      <material name="${name}_bottom_left_material">
        <color rgba="0.8 0.8 0.8 1"/>
      </material>
    </visual>
  </link>
  <gazebo reference="${name}_bottom_left">
    <material value="Gazebo/Grey"/>
  </gazebo>
  
  
  <!--  mount bottom right -->
  <joint name="${parent}_${name}_bottom_right_joint" type="fixed">
    <origin xyz="0.0 ${-mount_base_width} ${mount_bar_width/2.}" rpy="${rpy}"/>
    <parent link="${parent}"/>
    <child link="${name}_bottom_right"/>
  </joint>
  <link name="${name}_bottom_right">
    <visual>
      <origin xyz="-0.04 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.3 ${mount_bar_width} ${mount_bar_width}"/>
      </geometry>
      <material name="${name}_bottom_right_material">
        <color rgba="0.8 0.8 0.8 1"/>
      </material>
    </visual>
  </link>
  <gazebo reference="${name}_bottom_right">
    <material value="Gazebo/Grey"/>
  </gazebo>
  
  
  <!--  mount column right -->
  <joint name="${name}_column_right_joint" type="fixed">
    <origin xyz="0.0 0 ${0.92/2. + mount_bar_width}" rpy="${rpy}"/>
    <parent link="${name}_bottom_right"/>
    <child link="${name}_column_right"/>
  </joint>
  <link name="${name}_column_right">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${mount_bar_width} ${mount_bar_width} 0.92 "/>
      </geometry>
      <material name="${name}_column_right_material">
        <color rgba="0.8 0.8 0.8 1"/>
      </material>
    </visual>
  </link>
  <gazebo reference="${name}_column_right">
    <material value="Gazebo/Grey"/>
  </gazebo>
  
  
  
  <!--  mount column left -->
  <joint name="${name}_column_left_joint" type="fixed">
    <origin xyz="0.0 0 ${0.92/2. + mount_bar_width}" rpy="${rpy}"/>
    <parent link="${name}_bottom_left"/>
    <child link="${name}_column_left"/>
  </joint>
  <link name="${name}_column_left">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${mount_bar_width} ${mount_bar_width} 0.92 "/>
      </geometry>
      <material name="${name}_column_left_material">
        <color rgba="0.8 0.8 0.8 1"/>
      </material>
    </visual>
  </link>
  <gazebo reference="${name}_column_left">
    <material value="Gazebo/Grey"/>
  </gazebo>
  
  
  
  </xacro:macro>
</robot>
